####Comparing Pvalues from various tests
#Here pvals that were generated by different test procedures can be compared at different p-value thresholds,
#including their overlaps and joint thresholds.
library(abind)
library(reshape2)
library(dplyr)
library(ggplot2)
setwd("/Users/Moritz/Documents/Academic/RSMAS/PhD/SF16_GBS/Plots/pval_comparison")
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
cols=gg_color_hue(2)
#Populations
populations=c("Basin","Pond1","Pond2","Pond3")
snpnum=10861

#####Import the relevant p-value datasets
#Permutation pvalues need to be parsed since they are of different length
permfiles <- c("BaSU_vs_BaFT","P1SU_vs_P1FT","P2SU_vs_P2FT","P3SU_vs_P3FT")

permsraw <-list() #create list to store data of uneven length

#Read in the pvalues from the permutation analysis
for(i in permfiles) {
  permsraw[[i]] <- read.delim(paste("/Users/Moritz/Fuse_vols/STORAGE/SF16_GBS/perms/perm_thin/", i, "/pval/master.pval", sep=""), col.names = c("Chrom","Pos","He","FST","perms_in_He_range","perms_with_higher_Fst","p_val"))
}

pvals.perms <- permsraw[[1]] %>%
                full_join(permsraw[[2]], by=c("Chrom","Pos")) %>%
                full_join(permsraw[[3]], by=c("Chrom","Pos")) %>%
                full_join(permsraw[[4]], by=c("Chrom","Pos"))

pvals.perms <- pvals.perms[with(pvals.perms, order(Chrom,Pos)),c(7,12,17,22)]
rownames(pvals.perms) <- NULL
colnames(pvals.perms) <- populations
pvals.perms.melt <- melt(pvals.perms, variable.name = "Habitat", value.name = "pval")

#LOOKS LIKE ARLEQUIN DATA IS NOT RELIABLE
#Read in pvalues from Arlequin
#pvals.arl.raw <- read.delim("../../Arlequin/SF_fst_pval.txt")
#pvals.arl.raw$pval[which(pvals.arl.raw$FST<=0.015)] <- 1 #Have to set SNPs with low FST values to 1 since Arlequin gives them significant balancing selection
#pvals.arl.melt <- pvals.arl.raw[,c(1,3)] #Just keep pvalue information
#pvals.arl <- mutate(pvals.arl.melt, ID=rep(1:snpnum,4))
#pvals.arl <- dcast(pvals.arl, ID~Habitat, value.var = "pval")[,2:5]

#Read in pvalues from Simulations
pvals.sims <- read.delim("../simulations/simulation_pvals.txt")
pvals.sims.melt <- melt(pvals.sims, variable.name = "Habitat", value.name = "pval")
#Read in pvalues from Barnards Test
pvals.barnard <- read.delim("../Barnards Test/Barnard_pvals.txt")
pvals.barnard.melt <- melt(pvals.barnard, variable.name = "Habitat", value.name = "pval")

#Join all pvalue sets into an array, dimensions: (SNP:Population:Test)
tests <- c("Barnard's Test","Permutation","Simulation")
pvals.all.melt <- cbind(pvals.barnard.melt,
                   pvals.perms.melt[,2],
                   pvals.sims.melt[,2])
colnames(pvals.all.melt) <- c("Habitat","barnard","perms","sims")

#Export for future use
#write.table(pvals.all.melt, "temporal_pvals.no_arl.melt.txt", quote=F, sep="\t", row.names = F)

#Plot pvalue correlations
#png("pval_corr_SimsvsArl.png", width = 1200, height = 1200, res = 300)
ggplot(pvals.all.melt)+
  geom_point(aes(x=-log10(sims), y=-log10(arl), col=Habitat), alpha=.8)+
  labs(y=expression(-log[10]*"("*italic(p)~value*")"~"Arlequin"), x=expression(-log[10]*"("*italic(p)~value*")"~"Simulations"))+
  theme_bw()+ 
  theme(text = element_text(size=12), legend.position = c(0.85,0.2))
#dev.off()

#Find number of outliers for various p-value thresholds
#Make array of pval data, dimensions: (SNP:Populations:Test)
pvals.all <- abind(pvals.barnard,
                   pvals.perms,
                   pvals.sims,
                   along=3)

thresholds <- 10^-(seq(0.5,4,0.01))
outliernums <- array(NA, dim =c(length(thresholds),length(populations),length(tests)), dimnames=list(thresholds,populations,tests)) #Dimensions: (Threshold:Population:Test)

for(pop in 1:length(populations)){
  for(test in 1:length(tests)){
    for(th in 1:length(thresholds)){
    
    outliernums[th,pop,test] <- length(which(pvals.all[,pop,test]<=thresholds[th]))
    
    }
  }
}

exp <- matrix(rep(thresholds*snpnum,length(populations)), ncol = 4) #expected number of outlier SNPs
outliernums <- abind(exp,outliernums,along=3) #bind to array
dimnames(outliernums)[[3]] <- c("Expected",tests) #update dimnames

#Plotting observed vs expected number of outliers
#melt array into df

outliernums.melt <- melt(outliernums,varnames=c("threshold","population","Test"),value.name = "outliers")

png("obsVSexp_absolute.png", width = 2400, height = 2400, res = 300)
ggplot(outliernums.melt, aes(x=-log10(threshold), y=outliers, col=Test), alpha=.8)+
  geom_point()+
  geom_line()+
  scale_y_log10()+
  facet_wrap(~population)+
  labs(x=expression(-log[10]*"("*italic(p)~value*")"~"Threshold"), y="No. of significant SNPs")+
  theme_bw()+
  scale_color_manual(values = c("black",gg_color_hue(4)))+
  theme(text = element_text(size=24),
        legend.title = element_blank(),
        legend.text = element_text(size=12),
        legend.position = c(0.62,0.12),
        legend.background=element_blank(),
        legend.box.background = element_rect(colour = "black"))
dev.off()

#Calculate an O:E ratio i.e. observed vs. expected number of outliers
#Before doing the following, re-run the outliernums call without adding any information about expected numbers

oe_ratios <- array(NA, dim =c(length(thresholds),length(populations),length(tests)), dimnames=list(thresholds,populations,tests)) #Dimensions: (Threshold:Population:Test)

for(pop in 1:length(populations)){
  for(test in 1:length(tests)){
    for(th in 1:length(thresholds)){
      
      oe_ratios[th,pop,test] <- outliernums[th,pop,test]/(thresholds[th]*snpnum)
      
    }
  }
}

#Plot the OE ratios

oe_ratios.melt <- melt(oe_ratios,varnames=c("threshold","population","Test"),value.name = "oe_ratio")

png("obsVSexp_ratio_noarl.png", width = 2000, height = 2000, res = 300)
ggplot(oe_ratios.melt, aes(x=-log10(threshold), y=oe_ratio, col=Test), alpha=.8)+
  geom_hline(aes(yintercept=1), col="black", lty="twodash")+
  #geom_point()+
  geom_smooth(se=F, span=0.1)+
  #geom_line()+
  scale_y_log10(breaks = c(1,2,10,30))+
  facet_wrap(~population, ncol=2)+
  labs(x=expression(-log[10]*"("*italic(p)~value*")"~"Threshold"), y="Observed:Expected Ratio")+
  theme_bw()+
  scale_color_manual(values = c(gg_color_hue(4)))+
  theme(text = element_text(size=12),
        legend.title = element_blank(),
        legend.text = element_text(size=10),
        legend.position = c(0.12,0.9),
        legend.background=element_blank(),
        legend.box.background = element_rect(colour = "black"))
dev.off()