#!/bin/bash

#Job Name
#BSUB -J example_job

#Queue
#BSUB -q general

#Cores
#BSUB -n 4

#RAM per core (MB)
#BSUB -R "rusage[mem=4000]"

#Walltime (Optional)
#BSUB -W 24:00

#Project
#BSUB -P fun_gen_1

#Output File (Absolute path! Can use job name variable)
#BSUB -o /nethome/mae120/logs/example.out

###################################################################
#SETUP
#load modules
#change directory

#CODE
