#!/bin/bash

#Job Name
#BSUB -J example_job

#Project
#BSUB -P fun_gen_1

#Queue
#BSUB -q normal

#Cores
#BSUB -n 4

#RAM per core (Use M and G for Mb and Gb)
#BSUB -R "rusage[mem=4000M]"

#Walltime
#BSUB -W 01:00

#Output File (Absolute path! Can use job name variable)
#BSUB -o /nethome/mae120/logs/example_job.out

###################################################################
#SETUP
#change directory

#CODE
